ioPaths:

  # -
  #   - "Resource/Icon.qrc"
  #   - "View/resource.py"
  -
    - "Ui/PyBill.ui"
    - "View/PyBill.py"
  # -
  #   - "View/ErrorDisplay.ui"
  #   - "View/ErrorDisplay.py"
  # -
  #   - "Ui/SucessDisplay.ui"
  #   - "View/SucessDisplay.py"
  # -
  #   - "View/Create_storage.ui"
  #   - "View/Create_storage.py"


uic_options: --from-imports
init_package: False
force: True