# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View\addowe.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Add_owe(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(683, 704)
        self.tableWidget1 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget1.setGeometry(QtCore.QRect(20, 10, 641, 501))
        self.tableWidget1.setObjectName("tableWidget1")
        self.tableWidget1.setColumnCount(5)
        self.tableWidget1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(4, item)
        self.tableWidget1.verticalHeader().setVisible(False)
        self.tableWidget1.verticalHeader().setHighlightSections(False)
        self.AddOwe = QtWidgets.QPushButton(Dialog)
        self.AddOwe.setGeometry(QtCore.QRect(30, 520, 41, 31))
        self.AddOwe.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("View\\../Icon/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddOwe.setIcon(icon)
        self.AddOwe.setObjectName("AddOwe")
        self.DelOwe = QtWidgets.QPushButton(Dialog)
        self.DelOwe.setGeometry(QtCore.QRect(90, 520, 41, 31))
        self.DelOwe.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("View\\../Icon/Remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DelOwe.setIcon(icon1)
        self.DelOwe.setObjectName("DelOwe")
        self.SaveOwe = QtWidgets.QPushButton(Dialog)
        self.SaveOwe.setGeometry(QtCore.QRect(560, 650, 93, 28))
        self.SaveOwe.setObjectName("SaveOwe")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget1.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "欠款人"))
        item = self.tableWidget1.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "借款人"))
        item = self.tableWidget1.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "日期"))
        item = self.tableWidget1.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "金额"))
        item = self.tableWidget1.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "描述"))
        self.AddOwe.setToolTip(_translate("Dialog", "<html><head/><body><p>Add Own Record</p></body></html>"))
        self.DelOwe.setToolTip(_translate("Dialog", "<html><head/><body><p>Remove Own Record</p></body></html>"))
        self.SaveOwe.setText(_translate("Dialog", "OK"))
