# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yezil\Desktop\Project\pybill\Ui\Debt.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebtList(object):
    def setupUi(self, DebtList):
        DebtList.setObjectName("DebtList")
        DebtList.resize(683, 704)
        font = QtGui.QFont()
        font.setPointSize(12)
        DebtList.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Icon/bill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DebtList.setWindowIcon(icon)
        self.tableWidget1 = QtWidgets.QTableWidget(DebtList)
        self.tableWidget1.setGeometry(QtCore.QRect(20, 10, 641, 501))
        self.tableWidget1.setObjectName("tableWidget1")
        self.tableWidget1.setColumnCount(5)
        self.tableWidget1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(4, item)
        self.tableWidget1.verticalHeader().setVisible(False)
        self.tableWidget1.verticalHeader().setHighlightSections(False)
        self.AddOwe = QtWidgets.QPushButton(DebtList)
        self.AddOwe.setGeometry(QtCore.QRect(30, 520, 41, 31))
        self.AddOwe.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\yezil\\Desktop\\Project\\pybill\\Ui\\../Icon/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddOwe.setIcon(icon1)
        self.AddOwe.setObjectName("AddOwe")
        self.DelOwe = QtWidgets.QPushButton(DebtList)
        self.DelOwe.setGeometry(QtCore.QRect(90, 520, 41, 31))
        self.DelOwe.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\yezil\\Desktop\\Project\\pybill\\Ui\\../Icon/Remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DelOwe.setIcon(icon2)
        self.DelOwe.setObjectName("DelOwe")
        self.SaveOwe = QtWidgets.QPushButton(DebtList)
        self.SaveOwe.setGeometry(QtCore.QRect(560, 650, 93, 28))
        self.SaveOwe.setObjectName("SaveOwe")

        self.retranslateUi(DebtList)
        QtCore.QMetaObject.connectSlotsByName(DebtList)

    def retranslateUi(self, DebtList):
        _translate = QtCore.QCoreApplication.translate
        DebtList.setWindowTitle(_translate("DebtList", "Debt List"))
        item = self.tableWidget1.horizontalHeaderItem(0)
        item.setText(_translate("DebtList", "Debtor"))
        item = self.tableWidget1.horizontalHeaderItem(1)
        item.setText(_translate("DebtList", "Borrower"))
        item = self.tableWidget1.horizontalHeaderItem(2)
        item.setText(_translate("DebtList", "Date"))
        item = self.tableWidget1.horizontalHeaderItem(3)
        item.setText(_translate("DebtList", "Amount"))
        item = self.tableWidget1.horizontalHeaderItem(4)
        item.setText(_translate("DebtList", "Description"))
        self.AddOwe.setToolTip(_translate("DebtList", "<html><head/><body><p>Add Own Record</p></body></html>"))
        self.DelOwe.setToolTip(_translate("DebtList", "<html><head/><body><p>Remove Own Record</p></body></html>"))
        self.SaveOwe.setText(_translate("DebtList", "OK"))
from . import Icon_rc
