# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/zilinye/Documents/PyBill/Ui/PyBill.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 966)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(663, 741))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Icon/bill.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setMaximumSize(QtCore.QSize(1000, 60))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.NextMonth = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NextMonth.sizePolicy().hasHeightForWidth())
        self.NextMonth.setSizePolicy(sizePolicy)
        self.NextMonth.setMinimumSize(QtCore.QSize(91, 29))
        self.NextMonth.setMaximumSize(QtCore.QSize(91, 29))
        self.NextMonth.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NextMonth.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 150 , 254);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:8px;\n"
"    border-color:black;\n"
"    border-width:1px;\n"
"    border-style:solid;\n"
"\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 135 , 228);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border-color:grey;\n"
"    border-width:1px;\n"
"    border-style:solid;\n"
"}")
        self.NextMonth.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/Icon/Forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextMonth.setIcon(icon1)
        self.NextMonth.setObjectName("NextMonth")
        self.gridLayout_3.addWidget(self.NextMonth, 0, 2, 1, 1)
        self.PreviousMonth = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreviousMonth.sizePolicy().hasHeightForWidth())
        self.PreviousMonth.setSizePolicy(sizePolicy)
        self.PreviousMonth.setMinimumSize(QtCore.QSize(91, 29))
        self.PreviousMonth.setMaximumSize(QtCore.QSize(91, 29))
        self.PreviousMonth.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PreviousMonth.setStyleSheet("QPushButton\n"
"{\n"
"\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 150 , 254);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:8px;\n"
"    border-color:black;\n"
"    border-width:1px;\n"
"    border-style:solid;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 135 , 228);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border-color:grey;\n"
"    border-width:1px;\n"
"    border-style:solid;\n"
"}")
        self.PreviousMonth.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/Icon/Previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PreviousMonth.setIcon(icon2)
        self.PreviousMonth.setObjectName("PreviousMonth")
        self.gridLayout_3.addWidget(self.PreviousMonth, 0, 0, 1, 1)
        self.Month = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Month.setFont(font)
        self.Month.setText("")
        self.Month.setAlignment(QtCore.Qt.AlignCenter)
        self.Month.setObjectName("Month")
        self.gridLayout_3.addWidget(self.Month, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(600, 600))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("\n"
"QTableWidget                \n"
"{\n"
"    background:#FFFFFF;            // 整个表格控件 背景色\n"
"    border:none;                   // 整个表格控件 边框\n"
" \n"
"    font-size:12px;                // 所有字体大小\n"
"    color:#666666;                 // 所有字体颜色\n"
"}\n"
"\n"
"")
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(120)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("QPushButton\n"
"{\n"
"\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    \n"
"    background-color: rgb(230, 151, 68);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:8px;\n"
"    border-color:grey;\n"
"    border-width:1px;\n"
"    border-style:solid;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    \n"
"    background-color: rgb(255, 144, 47);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    \n"
"    \n"
"    background-color: rgb(255, 123, 7);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border-color:black;\n"
"    border-width:1px;\n"
"    border-style:solid;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.delRow = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delRow.setFont(font)
        self.delRow.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    \n"
"    background-color: rgb(230, 151, 68);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:8px;\n"
"    border-color:grey;\n"
"    border-width:1px;\n"
"    border-style:solid;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    \n"
"    background-color: rgb(255, 144, 47);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    \n"
"    \n"
"    background-color: rgb(255, 123, 7);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border-color:black;\n"
"    border-width:1px;\n"
"    border-style:solid;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/Icon/Remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delRow.setIcon(icon3)
        self.delRow.setObjectName("delRow")
        self.gridLayout_4.addWidget(self.delRow, 0, 1, 1, 1)
        self.addRow = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addRow.setFont(font)
        self.addRow.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    \n"
"    background-color: rgb(230, 151, 68);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:8px;\n"
"    border-color:grey;\n"
"    border-width:1px;\n"
"    border-style:solid;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    \n"
"    background-color: rgb(255, 144, 47);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    \n"
"    \n"
"    background-color: rgb(255, 123, 7);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    border-color:black;\n"
"    border-width:1px;\n"
"    border-style:solid;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/Icon/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addRow.setIcon(icon4)
        self.addRow.setObjectName("addRow")
        self.gridLayout_4.addWidget(self.addRow, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_3, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.OpenNew = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/Icon/icons8-open-parcel-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenNew.setIcon(icon5)
        self.OpenNew.setObjectName("OpenNew")
        self.AddNew = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/Icon/icons8-new-copy-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddNew.setIcon(icon6)
        self.AddNew.setObjectName("AddNew")
        self.save_change = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/Icon/icons8-save-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_change.setIcon(icon7)
        self.save_change.setObjectName("save_change")
        self.edit_person = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/Icon/user (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_person.setIcon(icon8)
        self.edit_person.setObjectName("edit_person")
        self.edit_cate = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/Icon/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_cate.setIcon(icon9)
        self.edit_cate.setObjectName("edit_cate")
        self.edit_owe = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/Icon/money-flow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_owe.setIcon(icon10)
        self.edit_owe.setObjectName("edit_owe")
        self.Calculate = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/Icon/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Calculate.setIcon(icon11)
        self.Calculate.setObjectName("Calculate")
        self.toolBar.addAction(self.AddNew)
        self.toolBar.addAction(self.OpenNew)
        self.toolBar.addAction(self.save_change)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.edit_person)
        self.toolBar.addAction(self.edit_cate)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.edit_owe)
        self.toolBar.addAction(self.Calculate)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyBill"))
        self.NextMonth.setToolTip(_translate("MainWindow", "<html><head/><body><p>Next Month</p></body></html>"))
        self.PreviousMonth.setToolTip(_translate("MainWindow", "<html><head/><body><p>Previous Month</p></body></html>"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Category"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Spend"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description"))
        self.delRow.setToolTip(_translate("MainWindow", "<html><head/><body><p>Remove Record</p></body></html>"))
        self.delRow.setText(_translate("MainWindow", "Delete"))
        self.addRow.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add New Record</p></body></html>"))
        self.addRow.setText(_translate("MainWindow", "Add"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.OpenNew.setText(_translate("MainWindow", "Open"))
        self.OpenNew.setToolTip(_translate("MainWindow", "Open New "))
        self.AddNew.setText(_translate("MainWindow", "AddNew"))
        self.AddNew.setToolTip(_translate("MainWindow", "Add New"))
        self.save_change.setText(_translate("MainWindow", "SaveChange"))
        self.save_change.setToolTip(_translate("MainWindow", "Save Change"))
        self.edit_person.setText(_translate("MainWindow", "EditPerson"))
        self.edit_person.setToolTip(_translate("MainWindow", "Edit Person"))
        self.edit_cate.setText(_translate("MainWindow", "EditCategory"))
        self.edit_cate.setToolTip(_translate("MainWindow", "EditCategory"))
        self.edit_owe.setText(_translate("MainWindow", "AddOwe"))
        self.edit_owe.setToolTip(_translate("MainWindow", "AddOwe"))
        self.Calculate.setText(_translate("MainWindow", "Calculate"))
        self.Calculate.setToolTip(_translate("MainWindow", "Calculate"))
from . import Icon_rc
