# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View\Report.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Report_Ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(849, 975)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.totalSpend = QtWidgets.QTextBrowser(Dialog)
        self.totalSpend.setGeometry(QtCore.QRect(150, 30, 221, 41))
        self.totalSpend.setObjectName("totalSpend")
        self.table2Widget = QtWidgets.QTableWidget(Dialog)
        self.table2Widget.setGeometry(QtCore.QRect(10, 160, 411, 241))
        self.table2Widget.setObjectName("table2Widget")
        self.table2Widget.setColumnCount(2)
        self.table2Widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.table2Widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.table2Widget.setHorizontalHeaderItem(1, item)
        self.table2Widget.horizontalHeader().setDefaultSectionSize(200)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(420, 30, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.averageSpend = QtWidgets.QTextBrowser(Dialog)
        self.averageSpend.setGeometry(QtCore.QRect(600, 30, 221, 41))
        self.averageSpend.setObjectName("averageSpend")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(570, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.list2Widget = QtWidgets.QListWidget(Dialog)
        self.list2Widget.setGeometry(QtCore.QRect(430, 160, 411, 241))
        self.list2Widget.setObjectName("list2Widget")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(350, 410, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 450, 681, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.chartLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.chartLayout.setContentsMargins(0, 0, 0, 0)
        self.chartLayout.setObjectName("chartLayout")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "总花销"))
        item = self.table2Widget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "姓名"))
        item = self.table2Widget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "实付金额"))
        self.label_2.setText(_translate("Dialog", "人均消费"))
        self.label_3.setText(_translate("Dialog", "转账操作"))
        self.label_4.setText(_translate("Dialog", "花费分布图"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
